// declare module 'react'
declare module 'gatsby'
declare module '@emotion/core'
declare module '@emotion/styled'
declare module 'tailwind.macro'
declare module 'react-use'
declare module 'react-intersection-observer'
declare module 'intersection-observer'
declare module 'uuid/v1'
declare module 'lodash'
declare module 'lodash/fp'
declare module 'gatsby-image'
declare module 'react-helmet'
declare module '@krapiva-org/utils'
declare module 'axios'
declare module 'gatsby-plugin-mailchimp'
declare module '*.svg'
